{% set name = "matplotlib-inline" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matplotlib_inline-{{ version }}.tar.gz
  sha256: 8423b23ec666be3d16e16b60bdd8ac4e86e840ebd1dd11a30b9f117f2fa0ab90

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - traitlets

test:
  imports:
    - matplotlib_inline
    - matplotlib_inline.backend_inline
  requires:
    - pip
    - matplotlib-base
    - ipython
  commands:
    - pip check
    - python -c 'from matplotlib_inline.backend_inline import show'

about:
  home: https://github.com/ipython/matplotlib-inline
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Inline Matplotlib backend for Jupyter
  dev_url: https://github.com/ipython/matplotlib-inline
  doc_url: https://github.com/ipython/matplotlib-inline/blob/master/README.md

extra:
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - martinRenou
